version: 2.1
orbs:
  docker: circleci/docker@0.6.0

jobs:
  build-latest: &template
    docker:
      - image: circleci/python:3.8.0
    environment:
      DJANGO_VERSION: 3.0
      DRF: 3.11
    executor: docker/docker
    steps:
      - checkout
      - run: echo "Django==$DJANGO_VERSION" > requirements.txt
      - run: echo "djangorestframework==$DRF" >> requirements.txt
      - run: pip install --user coveralls
      - run: pip install --user -r requirements.txt
      - run: pip install --user -r dev-requirements.txt
      - run:
          command: coverage run --source=dj_rest_auth setup.py test
          name: Test
  build-django-2:
    <<: *template
    environment:
      DJANGO_VERSION: 2.0
      DRF: 3.9

workflows:
  main:
    jobs:
      - build-latest
      - build-django-2